//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FynbusContext : DbContext
    {
        public FynbusContext()
            : base("name=FynbusContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicInformation> BasicInformations { get; set; }
        public virtual DbSet<HomeWagon> HomeWagons { get; set; }
        public virtual DbSet<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<PricePlan> PricePlans { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WagonDetail> WagonDetails { get; set; }
    }
}
