//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWagon
    {
        public int ID { get; set; }
        public string StreetName { get; set; }
        public short StreetNumber { get; set; }
        public short ZipCode { get; set; }
        public string City { get; set; }
        public string Municipality { get; set; }
    }
}
