//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offersform_SingleVehicle
    {
        public int ID { get; set; }
        public int BasicInformation { get; set; }
        public int WagonDetails { get; set; }
        public int Price { get; set; }
        public string AdditionalInformation { get; set; }
        public int OwnedBy { get; set; }
    
        public virtual BasicInformation BasicInformation1 { get; set; }
        public virtual Price Price1 { get; set; }
        public virtual WagonDetails WagonDetails1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
