//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePlan
    {
        public int ID { get; set; }
        public decimal SetUpFee { get; set; }
        public decimal HourlyRate { get; set; }
        public decimal HourlyDdownTime { get; set; }
    }
}
