//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BasicInformations = new HashSet<BasicInformation>();
            this.Offersform_SingleVehicle = new HashSet<Offersform_SingleVehicle>();
            this.Tokens = new HashSet<Token>();
            this.WagonDetails = new HashSet<WagonDetail>();
        }
    
        public int ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<byte> UsersAccessLevels { get; set; }
    
        public virtual ICollection<BasicInformation> BasicInformations { get; set; }
        public virtual ICollection<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<WagonDetail> WagonDetails { get; set; }
    }
}
