//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFynbusService.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WagonDetail
    {
        public WagonDetail()
        {
            this.Offersform_SingleVehicle = new HashSet<Offersform_SingleVehicle>();
            this.GuaranteeOf = new HashSet<WagonDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Guarantee { get; set; }
        public string RegistrationLetters { get; set; }
        public Nullable<int> RegistrationNumbers { get; set; }
        public int PhoneNumber { get; set; }
        public byte VehicleType { get; set; }
        public Nullable<byte> StairMachine { get; set; }
        public Nullable<byte> Highchairs { get; set; }
        public Nullable<int> HomeWagon { get; set; }
        public int OwnedBy { get; set; }
    
        public virtual HomeWagon ObjHomeWagon { get; set; }
        public virtual ICollection<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<WagonDetail> GuaranteeOf { get; set; }
        public virtual WagonDetail GuaranteeBy { get; set; }
    }
}
