//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicInformation
    {
        public BasicInformation()
        {
            this.Offersform_SingleVehicle = new HashSet<Offersform_SingleVehicle>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CVR { get; set; }
        public string NameSecondary { get; set; }
    
        public virtual ICollection<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
    }
}
