//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfFynbusContainer : DbContext
    {
        public EfFynbusContainer()
            : base("name=EfFynbusContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicInformation> BasicInformation { get; set; }
        public virtual DbSet<HomeWagon> HomeWagon { get; set; }
        public virtual DbSet<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<PricePlan> PricePlan { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WagonDetails> WagonDetails { get; set; }
    }
}
