//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePlan
    {
        public PricePlan()
        {
            this.Price = new HashSet<Price>();
            this.Price1 = new HashSet<Price>();
            this.Price2 = new HashSet<Price>();
        }
    
        public int ID { get; set; }
        public decimal SetUpFee { get; set; }
        public decimal HourlyRate { get; set; }
        public decimal HourlyDdownTime { get; set; }
    
        public virtual ICollection<Price> Price { get; set; }
        public virtual ICollection<Price> Price1 { get; set; }
        public virtual ICollection<Price> Price2 { get; set; }
    }
}
