//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public Price()
        {
            this.Offersform_SingleVehicle = new HashSet<Offersform_SingleVehicle>();
        }
    
        public int ID { get; set; }
        public int Weekdays { get; set; }
        public int WeekdaysEvening { get; set; }
        public int WeekendersHelligdage { get; set; }
        public Nullable<decimal> StairMachine { get; set; }
    
        public virtual ICollection<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual PricePlan PricePlan { get; set; }
        public virtual PricePlan PricePlan1 { get; set; }
        public virtual PricePlan PricePlan2 { get; set; }
    }
}
