//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Offersform_SingleVehicle = new HashSet<Offersform_SingleVehicle>();
            this.Token = new HashSet<Token>();
        }
    
        public int ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<byte> UsersAccessLevels { get; set; }
    
        public virtual ICollection<Offersform_SingleVehicle> Offersform_SingleVehicle { get; set; }
        public virtual ICollection<Token> Token { get; set; }
    }
}
