//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfInhous.ServiceInhous {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInhous.IInhous")]
    public interface IInhous {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInhous/GetOffers", ReplyAction="http://tempuri.org/IInhous/GetOffersResponse")]
        string GetOffers(string token, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInhous/GetOffers", ReplyAction="http://tempuri.org/IInhous/GetOffersResponse")]
        System.Threading.Tasks.Task<string> GetOffersAsync(string token, int index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInhousChannel : WpfInhous.ServiceInhous.IInhous, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InhousClient : System.ServiceModel.ClientBase<WpfInhous.ServiceInhous.IInhous>, WpfInhous.ServiceInhous.IInhous {
        
        public InhousClient() {
        }
        
        public InhousClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InhousClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InhousClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InhousClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetOffers(string token, int index) {
            return base.Channel.GetOffers(token, index);
        }
        
        public System.Threading.Tasks.Task<string> GetOffersAsync(string token, int index) {
            return base.Channel.GetOffersAsync(token, index);
        }
    }
}
